### ISSUE TITLE
I wish to help with testing on Windows and MacOS

### ISSUE THREAD

**Issue by chexo3** [project-grove/SDL2.NETCore#1]
I have both a Windows machine and MacOS machine available. I can probably compile it on my Windows machine for Windows, but I might have trouble producing a MacOS build to test. You may also wish to create some tests to verify behavior. I am relatively inexperienced with programming, but I have worked with XCode a little, and a little bit with Visual Studio.

**Comment by RaZeR-RBI** [comment]
Hello, and thank you for your feedback :wink:
Right now I don't have time to add tests to this project - the best thing you can do at the moment is to test some samples from my little framework named [Imagini](https://github.com/project-grove/imagini) which uses this wrapper. I've just recently pushed some code which should make game loop run a bit more precise (it needs verification on Windows though).
I have machines with W7/W8/W10 and I've tested Imagini on W7 just before that timing update and the samples worked for me, but they're kinda basic and use a very small portion of the SDL2 API, so if you have some experience with writing SDL2-based things and can cover more API than my samples do - it would be really great :+1:

**Comment by chexo3** [comment]
Good to know, thanks!
